name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
      
    - name: Build with PyInstaller
      run: |
        pyinstaller --name="YOLOv8_Trainer" --onefile --windowed --icon=icon.png --add-data="icon.png;." main.py
    
    # Alternative approach without using actions/upload-artifact
    - name: Create artifact directory
      run: mkdir artifacts
      
    - name: Copy executable to artifacts directory
      run: copy dist\YOLOv8_Trainer.exe artifacts\
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: YOLOv8_Trainer_Windows
        path: artifacts\YOLOv8_Trainer.exe
      with:
        name: YOLOv8_Trainer_Windows
        path: dist/YOLOv8_Trainer.exe
